### ISSUE TITLE
Pip install nina-helper Issue

### ISSUE THREAD

**Issue by erinqhu** [Lif3line/nina_helper_package_mk2#5]
Alireza ([asarmadi](https://github.com/parasgulati8/human_identification/commits?author=asarmadi)) and I also found that we got the nina_helper package (this version: https://github.com/Lif3line/nina_helper_package) installed on our device when using `pip install nina-helper`. When the package was successfully installed, the version shown in the terminal was actually 2.4. We confirmed this issue by checking the nina-helper package inside the site-packages folder of Anaconda3. To sum up, it seems like `pip install nina-helper` does not clone this version (https://github.com/Lif3line/nina_helper_package_mk2) to a user-defined directory.
Please let us know if it's a valid observation.
Thanks.

**Comment by Lif3line** [comment]
Good shout, looks like it's caused by a name clash with the old module, thanks for spotting it! Since I haven't implemented any CI/CD here, I've simply removed the reference to PyPi installation in the `readme` to prevent confusion. Now the recommended version is a local `pip` install.
